/**
 * Azure OpenAI-based image classifier for the RealityCheck API backend.
 *
 * Uses GPT-4o vision to determine whether an image is AI-generated.
 * Activated when the following environment variables are present:
 *
 *   AZURE_OPENAI_ENDPOINT    — Base URL including the /openai path, e.g.
 *                              https://hackathon2026-apim-chffbmwwvr7u2.azure-api.net/openai
 *   AZURE_OPENAI_API_KEY     — Azure OpenAI resource key
 *   AZURE_OPENAI_DEPLOYMENT  — model deployment name (default: gpt-5-1-chat)
 *   AZURE_OPENAI_API_VERSION — API version (default: 2024-10-21)
 *
 * When these variables are not set, the function is a no-op and the caller
 * falls back to the heuristic `analyzeImage` implementation.
 *
 * Chat completions endpoint format:
 *   POST {AZURE_OPENAI_ENDPOINT}/deployments/{deployment}/chat/completions
 *        ?api-version={version}
 * Authentication header: `Authorization: Bearer {key}` (APIM gateway format).
 */

export interface AzureOpenAIConfig {
  endpoint: string;
  apiKey: string;
  deployment: string;
  apiVersion: string;
}

/**
 * Read Azure OpenAI configuration from environment variables.
 * Returns null when the required variables are not set.
 */
export function getAzureOpenAIConfig(): AzureOpenAIConfig | null {
  const endpoint = process.env.AZURE_OPENAI_ENDPOINT?.trim();
  const apiKey = process.env.AZURE_OPENAI_API_KEY?.trim();
  if (!endpoint || !apiKey) {
    return null;
  }
  return {
    endpoint,
    apiKey,
    deployment: process.env.AZURE_OPENAI_DEPLOYMENT?.trim() || 'gpt-5-1-chat',
    apiVersion: process.env.AZURE_OPENAI_API_VERSION?.trim() || '2024-10-21',
  };
}

export interface OpenAIClassificationResult {
  score: number;
  label: 'ai' | 'human' | 'uncertain';
}

/**
 * Classify an image using Azure OpenAI GPT-4o vision.
 *
 * @param config        Azure OpenAI configuration.
 * @param imageDataUrl  Base64 data-URL of the (down-scaled) image, passed to the vision model.
 * @param imageUrl      Original source URL of the image (included in the prompt for extra context).
 * @returns Classification result with a 0–1 score and a label.
 * @throws When the Azure OpenAI API returns a non-2xx response.
 */
export async function classifyImageWithAzureOpenAI(
  config: AzureOpenAIConfig,
  imageDataUrl: string | undefined,
  imageUrl: string | undefined
): Promise<OpenAIClassificationResult> {
  const systemPrompt =
    'You are an AI-generated image detector. Analyse the provided image and determine whether it was ' +
    'generated by an AI model (e.g. DALL-E, Midjourney, Stable Diffusion) or captured by a real ' +
    'camera / created by a human artist. ' +
    'Respond with JSON only: {"score": <0.0-1.0 probability of AI generation>, ' +
    '"label": "<ai|human|uncertain>"}. ' +
    'Use score >= 0.65 for ai, score <= 0.35 for human, anything between for uncertain. Be conservative.';

  const userContent: unknown[] = [];
  if (imageDataUrl) {
    userContent.push({ type: 'image_url', image_url: { url: imageDataUrl } });
  }
  userContent.push({
    type: 'text',
    text: imageUrl
      ? `Image source URL: ${imageUrl}\nIs this image AI-generated? Respond with JSON only.`
      : 'Is this image AI-generated? Respond with JSON only.',
  });

  const chatUrl =
    `${config.endpoint.replace(/\/$/, '')}/deployments/${config.deployment}` +
    `/chat/completions?api-version=${config.apiVersion}`;

  const response = await fetch(chatUrl, {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
      Authorization: `Bearer ${config.apiKey}`,
    },
    body: JSON.stringify({
      messages: [
        { role: 'system', content: systemPrompt },
        { role: 'user', content: userContent },
      ],
      response_format: { type: 'json_object' },
      max_tokens: 64,
    }),
  });

  if (!response.ok) {
    throw new Error(`Azure OpenAI HTTP ${response.status}: ${response.statusText}`);
  }

  const data = (await response.json()) as {
    choices?: Array<{ message?: { content?: string } }>;
  };
  const raw = data?.choices?.[0]?.message?.content ?? '{}';
  let parsed: { score?: unknown; label?: unknown };
  try {
    parsed = JSON.parse(raw) as { score?: unknown; label?: unknown };
  } catch {
    parsed = {};
  }

  const score =
    typeof parsed.score === 'number' ? Math.min(1, Math.max(0, parsed.score)) : 0.5;
  const labelRaw = typeof parsed.label === 'string' ? parsed.label : 'uncertain';
  const label: OpenAIClassificationResult['label'] =
    labelRaw === 'ai' || labelRaw === 'human' ? labelRaw : 'uncertain';

  return { score, label };
}
