/**
 * Azure OpenAI-based image classifier for the RealityCheck API backend.
 *
 * Uses the Azure OpenAI Responses API to determine whether an image is AI-generated.
 * Activated when the following environment variables are present:
 *
 *   AZURE_OPENAI_ENDPOINT    — Base URL including the /openai path, e.g.
 *                              https://hackathon2026-apim-chffbmwwvr7u2.azure-api.net/openai
 *   AZURE_OPENAI_API_KEY     — Bearer token for APIM gateway authentication
 *   AZURE_OPENAI_DEPLOYMENT  — model deployment name (default: gpt-5-1-chat)
 *
 * When these variables are not set, the function is a no-op and the caller
 * falls back to the heuristic `analyzeImage` implementation.
 *
 * Responses API endpoint format:
 *   POST {AZURE_OPENAI_ENDPOINT}/v1/responses
 * Authentication header: `Authorization: Bearer {key}` (APIM gateway format).
 */

export interface AzureOpenAIConfig {
  endpoint: string;
  apiKey: string;
  deployment: string;
}

/**
 * Read Azure OpenAI configuration from environment variables.
 * Returns null when the required variables are not set.
 */
export function getAzureOpenAIConfig(): AzureOpenAIConfig | null {
  const endpoint = process.env.AZURE_OPENAI_ENDPOINT?.trim();
  const apiKey = process.env.AZURE_OPENAI_API_KEY?.trim();
  if (!endpoint || !apiKey) {
    return null;
  }
  return {
    endpoint,
    apiKey,
    deployment: process.env.AZURE_OPENAI_DEPLOYMENT?.trim() || 'gpt-5-1-chat',
  };
}

export interface OpenAIClassificationResult {
  score: number;
  label: 'ai' | 'human' | 'uncertain';
}

/**
 * Classify an image using Azure OpenAI Responses API (vision).
 *
 * @param config        Azure OpenAI configuration.
 * @param imageDataUrl  Base64 data-URL of the (down-scaled) image, passed to the vision model.
 * @param imageUrl      Original source URL of the image (included in the prompt for extra context).
 * @returns Classification result with a 0–1 score and a label.
 * @throws When the Azure OpenAI API returns a non-2xx response.
 */
export async function classifyImageWithAzureOpenAI(
  config: AzureOpenAIConfig,
  imageDataUrl: string | undefined,
  imageUrl: string | undefined
): Promise<OpenAIClassificationResult> {
  const systemPrompt =
    'You are an AI-generated image detector. Analyse the provided image and determine whether it was ' +
    'generated by an AI model (e.g. DALL-E, Midjourney, Stable Diffusion) or captured by a real ' +
    'camera / created by a human artist. ' +
    'Respond with JSON only: {"score": <0.0-1.0 probability of AI generation>, ' +
    '"label": "<ai|human|uncertain>"}. ' +
    'Use score >= 0.65 for ai, score <= 0.35 for human, anything between for uncertain. Be conservative.';

  const userContent: unknown[] = [];
  if (imageDataUrl) {
    userContent.push({ type: 'input_image', image_url: imageDataUrl });
  }
  userContent.push({
    type: 'input_text',
    text: imageUrl
      ? `Image source URL: ${imageUrl}\nIs this image AI-generated? Respond with JSON only.`
      : 'Is this image AI-generated? Respond with JSON only.',
  });

  const responsesUrl = `${config.endpoint.replace(/\/$/, '')}/v1/responses`;

  const response = await fetch(responsesUrl, {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
      Authorization: `Bearer ${config.apiKey}`,
    },
    body: JSON.stringify({
      model: config.deployment,
      input: [
        { role: 'system', content: systemPrompt },
        { role: 'user', content: userContent },
      ],
      text: {
        format: {
          type: 'json_schema',
          name: 'AIDetectionResult',
          schema: {
            type: 'object',
            properties: {
              score: { type: 'number' },
              label: { type: 'string' },
            },
            required: ['score', 'label'],
            additionalProperties: false,
          },
          strict: true,
        },
      },
    }),
  });

  if (!response.ok) {
    throw new Error(`Azure OpenAI HTTP ${response.status}: ${response.statusText}`);
  }

  // Responses API returns: { output: [{ type: "message", content: [{ type: "output_text", text: "..." }] }] }
  const data = (await response.json()) as {
    output?: Array<{
      type?: string;
      content?: Array<{ type?: string; text?: string }>;
    }>;
    output_text?: string;
  };

  const raw =
    data.output_text ??
    data.output?.find((o) => o.type === 'message')?.content?.find((c) => c.type === 'output_text')?.text ??
    '{}';

  let parsed: { score?: unknown; label?: unknown };
  try {
    parsed = JSON.parse(raw) as { score?: unknown; label?: unknown };
  } catch {
    parsed = {};
  }

  const score =
    typeof parsed.score === 'number' ? Math.min(1, Math.max(0, parsed.score)) : 0.5;
  const labelRaw = typeof parsed.label === 'string' ? parsed.label : 'uncertain';
  const label: OpenAIClassificationResult['label'] =
    labelRaw === 'ai' || labelRaw === 'human' ? labelRaw : 'uncertain';

  return { score, label };
}
